[2024-04-25T02:30:27.659+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-25T02:30:27.680+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_task_dag.load_warehouse manual__2024-04-25T02:29:59.765338+00:00 [queued]>
[2024-04-25T02:30:27.685+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_task_dag.load_warehouse manual__2024-04-25T02:29:59.765338+00:00 [queued]>
[2024-04-25T02:30:27.685+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-25T02:30:27.698+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_warehouse> on 2024-04-25 02:29:59.765338+00:00
[2024-04-25T02:30:27.707+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_task_dag', 'load_warehouse', 'manual__2024-04-25T02:29:59.765338+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/DataMLOps.py', '--cfg-path', '/tmp/tmpjjjwkgl_']
[2024-04-25T02:30:27.709+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask load_warehouse
[2024-04-25T02:30:27.710+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2436) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-25T02:30:27.711+0000] {standard_task_runner.py:63} INFO - Started process 2451 to run task
[2024-04-25T02:30:27.739+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_task_dag.load_warehouse manual__2024-04-25T02:29:59.765338+00:00 [running]> on host 4d4cdcf2282e
[2024-04-25T02:30:27.795+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_task_dag' AIRFLOW_CTX_TASK_ID='load_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T02:29:59.765338+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-25T02:29:59.765338+00:00'
[2024-04-25T02:30:27.796+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-25T02:30:27.927+0000] {logging_mixin.py:188} INFO - Database 'bt4301_gp_datawarehouse' already exists. No need to create it.
[2024-04-25T02:30:27.934+0000] {logging_mixin.py:188} INFO - MySQL connection is closed
[2024-04-25T02:30:28.465+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/DataMLOps.py:477 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-04-25T02:30:32.410+0000] {logging_mixin.py:188} WARNING - 2024-04-25 02:30:32.410 
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /home/***/.local/bin/*** [ARGUMENTS]
[2024-04-25T02:30:34.258+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-25T02:30:34.259+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-25T02:30:34.264+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=daily_task_dag, task_id=load_warehouse, execution_date=20240425T022959, start_date=20240425T023027, end_date=20240425T023034
[2024-04-25T02:30:34.288+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-25T02:30:34.305+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-25T02:30:34.309+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
