[2024-04-23T18:01:01.119+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-23T18:01:01.141+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_task_dag.load_warehouse manual__2024-04-23T18:00:32.127959+00:00 [queued]>
[2024-04-23T18:01:01.147+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_task_dag.load_warehouse manual__2024-04-23T18:00:32.127959+00:00 [queued]>
[2024-04-23T18:01:01.147+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-23T18:01:01.160+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_warehouse> on 2024-04-23 18:00:32.127959+00:00
[2024-04-23T18:01:01.171+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_task_dag', 'load_warehouse', 'manual__2024-04-23T18:00:32.127959+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/DataMLOps.py', '--cfg-path', '/tmp/tmp7qwx5fkc']
[2024-04-23T18:01:01.173+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask load_warehouse
[2024-04-23T18:01:01.175+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=269) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-23T18:01:01.175+0000] {standard_task_runner.py:63} INFO - Started process 282 to run task
[2024-04-23T18:01:01.208+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_task_dag.load_warehouse manual__2024-04-23T18:00:32.127959+00:00 [running]> on host b20e8c8b6af3
[2024-04-23T18:01:01.272+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_task_dag' AIRFLOW_CTX_TASK_ID='load_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T18:00:32.127959+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T18:00:32.127959+00:00'
[2024-04-23T18:01:01.273+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-23T18:01:01.410+0000] {logging_mixin.py:188} INFO - Database 'bt4301_gp_datawarehouse' already exists. No need to create it.
[2024-04-23T18:01:01.418+0000] {logging_mixin.py:188} INFO - MySQL connection is closed
[2024-04-23T18:01:01.966+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/DataMLOps.py:477 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-04-23T18:01:06.017+0000] {logging_mixin.py:188} WARNING - 2024-04-23 18:01:06.017 
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /home/***/.local/bin/*** [ARGUMENTS]
[2024-04-23T18:01:07.715+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-23T18:01:07.716+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-23T18:01:07.723+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=daily_task_dag, task_id=load_warehouse, execution_date=20240423T180032, start_date=20240423T180101, end_date=20240423T180107
[2024-04-23T18:01:07.758+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-23T18:01:07.775+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-23T18:01:07.779+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
